auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/add", views.add_listing, name="add_listing"),
    path("listing/<int:listing_id>", views.listing_page, name="listing_page"),
    path("listing/<int:listing_id>/bid", views.place_bid, name="place_bid"),
    path("listing/<int:listing_id>/comment", views.post_comment, name="post_comment"),
    path("listing/<int:listing_id>/close", views.close_listing, name="close_listing"),
    path("listing/<int:listing_id>/watchlist/add", views.watchlist_add, name="watchlist_add"),
    path("listing/<int:listing_id>/watchlist/remove", views.watchlist_remove, name="watchlist_remove"),
    path("user/<str:username>/listings", views.user_listings, name="user_listings"),
    path("user/<str:username>/watchlist", views.watchlist, name="watchlist"),
    path("user/<str:username>/comments", views.user_comments, name="user_comments"),
    path("categories", views.categories, name="categories")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class User(AbstractUser):
    pass


class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    image_url = models.CharField(max_length=160, blank=True)

    # Categories
    BRAND_CHOICES = [
        ("AP", "Apple"),
        ("SM", "Samsung"),
        ("NK", "Nokia"),
    ]
    TYPE_CHOICES = [
        ("LUX", "Luxury"),
        ("LTS", "Latest Model"),
        ("OLD", "Older Model"),
        ("LEG", "Legacy"),
    ]
    CONDITION_CHOICES = [
        ("N", "New"),
        ("U", "Used"),
        ("B", "Broken"),
    ]
    brand = models.CharField(
        max_length=2,
        choices=BRAND_CHOICES,
        blank=True,
    )
    type = models.CharField(
        max_length=3,
        choices=TYPE_CHOICES,
        blank=True,
    )
    condition = models.CharField(
        max_length=1,
        choices=CONDITION_CHOICES,
        blank=True,
    )

    # https://stackoverflow.com/questions/849142/how-to-limit-the-maximum-value-of-a-numeric-field-in-a-django-model
    starting_price = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999999)])
    current_price = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999999)])

    date = models.DateTimeField(auto_now_add=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    active = models.BooleanField(default=True)
    watchers = models.ManyToManyField(User, blank=True, related_name="watchlist")
    
    def __str__(self):
        return f"{self.title}"
    

class Bid(models.Model):
    value = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999999)])
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")

    def __str__(self):
        return f"{self.bidder} has placed a bid of ${self.value} for Listing: {self.listing}"


class Comment(models.Model):
    message = models.TextField()
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} commented \"{self.message}\" on Listing: {self.listing}"

auctions/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from crispy_forms.bootstrap import Div, FormActions

from .models import Listing, Bid, Comment

# Source: https://ordinarycoders.com/blog/article/django-modelforms

# Create your forms here.
class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ("title", "description", "starting_price", "image_url", "brand", "type", "condition")


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ("value",)
        widgets = {
            "value": forms.NumberInput(attrs={"placeholder": "Bid"}),
        }
        labels = {
            "value": "",
        }

    # https://stackoverflow.com/questions/17830470/get-request-in-form-field-validation
    def __init__(self, *args, **kwargs):
        self.listing_id = kwargs.pop('listing_id', None)
        super(BidForm, self).__init__(*args, **kwargs)

    def clean(self):

        # https://www.geeksforgeeks.org/python-form-validation-using-django/
        super(BidForm, self).clean()

        value = self.cleaned_data.get("value")

        listing = Listing.objects.get(pk=self.listing_id)

        try:
            # Ensure bid placed is higher than highest bid
            highest_bid = listing.bids.order_by('-value')[0].value
            if not value > highest_bid:
                self._errors['value'] = self.error_class([
                f'Bid should be more than ${highest_bid}']) 
        except IndexError:
            # Ensure bid placed at least equal to starting price
            if not value >= listing.starting_price:
                self._errors['value'] = self.error_class([
                f'Bid should be at least ${listing.starting_price}'])             

        return self.cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("message",)
        widgets = {
            "message": forms.Textarea(attrs={
                "placeholder": "Add a comment...",
                "rows": "2",
            }),
        }
        labels = {
            "message": "",
        }


class CategoriesForm(forms.ModelForm):

    # https://stackoverflow.com/questions/46892518/inline-form-with-django-crispy-form
    def __init__(self, *args, **kwargs):
        super(CategoriesForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
        Div(
            Div("brand", css_class="col"),
            Div("type", css_class="col"),
            Div("condition", css_class="col"),
            Div(
                FormActions(Submit('submit', 'Filter')),
                css_class="col-auto categories-button"
            ),
            css_class='row container-fluid mx-auto',
        ))


    class Meta:
        model = Listing
        fields = ("brand", "type", "condition")

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Listing, Bid, Comment
from .forms import ListingForm, BidForm, CommentForm, CategoriesForm


def index(request):
    """ Shows currently active listings """

    return render(request, "auctions/index.html", {
        "listings": Listing.objects.filter(active=True).order_by('-date'),
    })


@login_required
def add_listing(request):
    """ Allows a user to create a listing """

    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            # https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/#the-save-method
            listing = form.save(commit=False)
            listing.seller = request.user
            listing.current_price = listing.starting_price
            listing.save()
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/add_listing.html", {
                "form": form,
                "message": "Failed to add listing.",
            })
    else:
        return render(request, "auctions/add_listing.html", {
            "form": ListingForm()
        })


def listing_page(request, listing_id):
    """ Shows information for given listing """

    # Get listing info
    listing = Listing.objects.get(pk=listing_id)

    msg = request.session.get("msg")
    request.session["msg"] = None

    return render(request, "auctions/listing_page.html", {
        "listing": listing,
        "bid_form": BidForm(),
        "comment_form": CommentForm(),
        "msg": msg,
    })


@login_required
def place_bid(request, listing_id):
    """ Allows user to place bid on listing """
    if request.method == "POST":
        listing = Listing.objects.get(pk=listing_id)
        form = BidForm(request.POST, listing_id=listing_id)

        if form.is_valid():
            # Save bid data
            bid = form.save(commit=False)
            bid.listing = listing
            bid.bidder = request.user
            bid.save()

            # Update current price
            listing.current_price = bid.value
            listing.save()
            
            # Auto add listing to watchlist
            if listing not in request.user.watchlist.all():
                listing.watchers.add(request.user) 
                request.session["msg"] = {"msg": "Bid placed successfully. Listing added to watchlist.", "class": "alert-success"}
            else:
                request.session["msg"] = {"msg": "Bid placed successfully.", "class": "alert-success"}

            return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))
        else:
            return render(request, "auctions/listing_page.html", {
                "listing": listing,
                "bid_form": form,
                "comment_form": CommentForm(),
                "msg": {"msg": "Failed to place bid.", "class": "alert-danger"}
            })
    else:
        return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))


@login_required
def post_comment(request, listing_id):
    """ Allows user to post comment on listing """

    if request.method == "POST":
        listing = Listing.objects.get(pk=listing_id)
        form = CommentForm(request.POST)

        if form.is_valid():
            # Save comment data
            comment = form.save(commit=False)
            comment.listing = listing
            comment.author = request.user
            comment.save()
            
            request.session["msg"] = {"msg": "Comment posted!", "class": "alert-success"}

            return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))
        else:
            return render(request, "auctions/listing_page.html", {
                "listing": listing,
                "bid_form": BidForm(),
                "comment_form": form,
                "msg": {"msg": "Failed to post comment.", "class": "alert-danger"}
            })
    else:
        return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))


@login_required
def close_listing(request, listing_id):
    """ Allows seller to close their listing """

    if request.method == "POST":
        listing = Listing.objects.get(pk=listing_id)
        if request.user == listing.seller:
            listing.active = False
            listing.save()
            request.session["msg"] = {"msg": "Listing has been closed!", "class": "alert-success"}

    return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))


def user_listings(request, username):
    """ Displays all listings created by a specified user """

    seller = User.objects.get(username=username)

    return render(request, "auctions/user_listings.html", {
        "seller": seller,
        "listings": seller.listings.all().order_by('-date'),
    })


def user_comments(request, username):
    """ Displays all comments posted by a specified user """

    author = User.objects.get(username=username)

    return render(request, "auctions/user_comments.html", {
        "username": username,
        "comments": Comment.objects.filter(author=author).order_by("-date"),
    })


@login_required
def watchlist(request, username):
    """ Displays all listings in user's own watchlist """

    # Redirect to own watchlist if trying to view someone else's
    if request.user.username != username:
        return HttpResponseRedirect(reverse("watchlist", args=[request.user.username]))

    return render(request, "auctions/watchlist.html", {
        "listings": request.user.watchlist.all().order_by('-date'),
    })


@login_required
def watchlist_add(request, listing_id):
    """ Allows a user to add a listing to their watchlist """

    if request.method == "POST":
        listing = Listing.objects.get(pk=listing_id)
        listing.watchers.add(request.user)
        listing.save()
        request.session["msg"] = {"msg": "Listing has been added to watchlist!", "class": "alert-success"}

    return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))


@login_required
def watchlist_remove(request, listing_id):
    """ Allows a user to remove a listing from their watchlist """

    if request.method == "POST":
        listing = Listing.objects.get(pk=listing_id)
        listing.watchers.remove(request.user)
        listing.save()
        request.session["msg"] = {"msg": "Listing has been removed from watchlist!", "class": "alert-success"}

    return HttpResponseRedirect(reverse("listing_page", args=[listing_id]))


def categories(request):
    """ Allow users to filter for specific categories """

    listings = Listing.objects.filter(active=True).order_by('-date')
    form = CategoriesForm()

    if request.method == "POST":
        form = CategoriesForm(request.POST)
        if form.is_valid():
            # Filters listings based on selected categories
            if form.cleaned_data["brand"]:
                listings = listings.filter(brand=form.cleaned_data["brand"])
            if form.cleaned_data["type"]:
                listings = listings.filter(type=form.cleaned_data["type"])
            if form.cleaned_data["condition"]:
                listings = listings.filter(condition=form.cleaned_data["condition"])

    return render(request, "auctions/categories.html", {
        "listings": listings,
        "categories_filter": form,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/add_listing.html
{% extends "auctions/layout.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Create Listing
{% endblock %}

{% block body %}

    <div class="container">
        <h2>Create New Listing</h2>

        {% if message %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}

        <div class="my-4">
            <form action="{% url 'add_listing' %}" method="post">
                <!-- https://ordinarycoders.com/blog/article/render-a-django-form-with-bootstrap -->
                {% csrf_token %}
                {{ form | crispy }}
                <input class="btn btn-primary" type="submit" value="Save">
            </form>
        </div>
    </div>
    
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/listings_list.html" %}

{% load custom_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Categories
{% endblock %}

{% block heading %}
    Categories
{% endblock %}

{% block filter_form %}
    <form action="{% url 'categories' %}" method="post">
        {% crispy categories_filter %}
    </form>
{% endblock %}

{% block badges %}
    {% categories_badge listing as categories %}
    {% if categories %}
        <p class="small mb-0">{{ categories | safe }}</p>
    {% endif %}
{% endblock %}

{% block empty_msg %}
    No currently active listings based on your filters.
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/listings_list.html" %}

{% load custom_filters %}

{% block title %}
    Active Listings
{% endblock %}

{% block heading %}
    Active Listings
{% endblock %}

{% block badges %}
    {% categories_badge listing as categories %}
    {% if categories %}
        <p class="small mb-0">{{ categories | safe }}</p>
    {% endif %}
{% endblock %}

{% block empty_msg %}
    No currently active listings.
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Phone Auctions{% endblock %}</title>

        <!-- -Bootstrap 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

        <!-- Font Awesome Icons -->
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Phone Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' user.username %}">
                        Watchlist
                        <span class="badge bg-secondary">{{ user | watchlist_count }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item ms-auto">
                    <a class="nav-link" href="{% url 'user_listings' user.username %}">My Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_comments' user.username %}">My Comments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr class="mt-1">
        {% block body %}
        {% endblock %}

        <!-- Bootstrap 5 -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </body>
</html>

auctions/templates/auctions/listing_page.html
{% extends "auctions/layout.html" %}

{% load crispy_forms_tags %}
{% load custom_filters %}

{% block title %}
    Listing: {{ listing.title }}
{% endblock %}

{% block body %}
    <div class="container">
        {% if msg %}
            <div class="alert {{ msg.class }} alert-dismissible" role="alert">
                {{ msg.msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}

        {% if not listing.active %}
            {% bid_result user listing as bid_result %}
            {{ bid_result | safe }}
        {% endif %}

        <h2 class="fw-bold">Listing: {{ listing.title }}</h2>

        {% if not listing.active %}
            <span class="badge text-bg-danger mb-2">Closed</span>
        {% endif %}

        {% if user.is_authenticated and user != listing.seller %}
            {% is_watching user listing as is_watching %}
            {% if is_watching %}
                <form action="{% url 'watchlist_remove' listing.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger">
                        <i class="fa-solid fa-eye-slash small"></i>
                        Remove from Watchlist
                    </button>
                </form>
            {% else %}
                <form action="{% url 'watchlist_add' listing.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-primary">
                        <i class="fa-solid fa-eye small"></i>
                        Add to Watchlist
                    </button>
                </form>
            {% endif %}
        {% endif %}
        

        {% if user == listing.seller and listing.active %}
            <form action="{% url 'close_listing' listing.id %}" method="post">
                {% csrf_token %}
                <input class="btn btn-sm btn-danger" type="submit" value="Close Auction">
            </form>
        {% endif %}

        {% if listing.image_url %}
            <div class="listing-image-container text-center">
                <img class="listing-image" src="{{ listing.image_url }}" alt="{{ listing.title }}">
            </div>
        {% else %}
            <p class="text-center my-5">No Image Available</p>
        {% endif %}

        <p class="my-1">{{ listing.description }}</p>

        <h3 class="mt-3 fw-bold">${{ listing.current_price | number_commas }}</h3>

        {% bid_status_message user listing as bid_status %}
        {% if user.is_authenticated and listing.active and request.user != listing.seller %}
            <form action="{% url 'place_bid' listing.id %}" method="post">
                {% csrf_token %}
                {{ bid_status | safe }}
                {{ bid_form | crispy }}
                <input class="btn btn-primary" type="submit" value="Place Bid">
            </form>
        {% else %}
            {{ bid_status | safe }}
        {% endif %}

        <h4 class="mt-4">Details</h4>
        <ul>
            <li><span class="fw-semibold">Listed by:</span> <a href="{% url 'user_listings' listing.seller.username %}" class="fw-bold link-underline link-underline-opacity-0 link-underline-opacity-100-hover">{{ listing.seller }}</a></li>
            <li><span class="fw-semibold">Created:</span> {{ listing.date }}</li>
            <li>
                <span class="fw-semibold">Brand: </span> 
                {% if listing.get_brand_display %}
                    {{ listing.get_brand_display }}
                {% else %}
                    <span class="text-danger fw-semibold">Not Listed</span>
                {% endif %}
            </li>
            <li>
                <span class="fw-semibold">Type: </span>
                {% if listing.get_type_display %}
                    {{ listing.get_type_display }}
                {% else %}
                    <span class="text-danger fw-semibold">Not Listed</span>
                {% endif %}
            </li>
            <li>
                <span class="fw-semibold">Condition: </span>
                {% if listing.get_condition_display %}
                    {{ listing.get_condition_display }}
                {% else %}
                    <span class="text-danger fw-semibold">Not Listed</span>
                {% endif %}
            </li>
        </ul>

        {% comment_count listing as comment_count %}
        {{ comment_count | safe }}
        {% if user.is_authenticated %}
            <form action="{% url 'post_comment' listing.id %}" method="post">
                {% csrf_token %}
                {{ comment_form | crispy }}
                <div class="text-end">
                    <input class="btn btn-primary" type="submit" value="Comment">
                </div>
            </form>
        {% endif %}

        {% get_comments listing as comments %}
        {% for comment in comments %}
            <p class="mb-1">
                <a href="{% url 'user_comments' comment.author.username %}" class="fw-bold link-underline link-underline-opacity-0 link-underline-opacity-100-hover">@{{ comment.author }}</a>
                <span class="small text-muted">{{ comment.date | time_ago }}</span>
            </p>
            <p>{{ comment.message }}</p>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/listings_list.html
{% extends "auctions/layout.html" %}

{% load custom_filters %}

{% block body %}
    <h2>{% block heading %}{% endblock %}</h2>

    {% block filter_form %}{% endblock %}

    {% for listing in listings %}
        <a href="{% url 'listing_page' listing.id %}" class="text-reset text-decoration-none">
            <div class="row listing-group mx-5 my-3 border rounded">
                <div class="col-3 text-center h-100 flex-centered">
                    {% if listing.image_url %}
                        <img class="listing-image" src="{{ listing.image_url }}" alt="{{ listing.title }}">
                    {% else %}
                        <p>No Image Available</p>
                    {% endif %}
                </div>
                <div class="col-9">
                    <h4 class="mt-3 fw-bold">{{ listing.title }}</h4>

                    {% block badges %}{% endblock %}

                    <p class="fw-bold my-1">Price: ${{ listing.current_price | number_commas }}</p>
                    <p class="my-1">{{ listing.description | cutoff }}</p>
                    <p class="text-muted small my-1">Created {{ listing.date | time_ago }}</p>
                </div>
            </div>
        </a>
    {% empty %}
        <p>{% block empty_msg %}{% endblock %}</p>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <h2>Login</h2>

        {% if message %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endif %}

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="my-3">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username" required>
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
            <input class="btn btn-primary mb-3" type="submit" value="Login">
        </form>

        Don't have an account? <a href="{% url 'register' %}">Register here.</a>

    </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="container">
        <h2>Register</h2>

        {% if message %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endif %}

        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="my-3">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username" required>
            </div>
            <div class="mb-3">
                <input class="form-control" type="email" name="email" placeholder="Email Address" required>
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
            </div>
            <input class="btn btn-primary mb-3" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </div>
{% endblock %}

auctions/templates/auctions/user_comments.html
{% extends "auctions/layout.html" %}

{% block title %}
    {{ username }}'s Comments
{% endblock %}

{% block body %}
    <h2>{{ username }}'s Comments</h2>

    <div class="mx-3">
        {% for comment in comments %}
            <div class="border rounded py-2 px-3">
                <p class="small mb-1 text-secondary">Commented on Listing: 
                    <a href="{% url 'listing_page' comment.listing.id %}" class="fw-bold link-underline link-underline-opacity-0 link-underline-opacity-100-hover">{{ comment.listing }}</a>
                </p>
                <p class="my-2">{{ comment.message }}</p>
            </div>
        {% empty %}
            {{ username }} has not posted any comments.
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/user_listings.html
{% extends "auctions/listings_list.html" %}

{% load custom_filters %}

{% block title %}
    {{ seller.username }}'s Listings
{% endblock %}

{% block heading %}
    {{ seller.username }}'s Listings
{% endblock %}

{% block badges %}
    <p class="mb-0 small">
        {% if listing.active %}
            <span class="badge text-bg-success">Active</span>
        {% else %}
            <span class="badge text-bg-danger">Closed</span>
        {% endif %}
        
        {% categories_badge listing as categories %}
        {{ categories | safe }}    
    </p>
{% endblock %}

{% block empty_msg %}
    {{ seller }} has not created any listings.
{% endblock %}